### ISSUE TITLE
[Pertanyaan] Maaf kak aku open issue, bingung mau reach kak kemana.

### ISSUE THREAD

**Issue by BidjiKekar** [FutureSeekerTech/fs-guard#2]
Pertanyaanku:
1. Apakah guard ini masih work untuk sekarang?
2. Gimana ya caranya biar bisa test trigger event yg belum di secure, jd biar tau event mana aja yg perlu di secure.

**Comment by alfaritsii** [comment]
> Pertanyaanku:
> 
>     1. Apakah guard ini masih work untuk sekarang?
> 
>     2. Gimana ya caranya biar bisa test trigger event yg belum di secure, jd biar tau event mana aja yg perlu di secure.

Halo, untuk guard ini karena open source memiliki kerentanan karena metode nya dapat dibaca oleh siapa saja dan versi untuk private dan terbarunya hanya ada di discord server saya. Disitu sudah ada penjelasan gimana caranya untuk melakukan pengetesannya. Discord invite link: https:discord.gg/TRwcswBhg3
